# Generated by Django 3.1.1 on 2020-09-26 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='info name')),
                ('season', models.IntegerField(choices=[(1, 'S/S'), (2, 'A/W')], default=1, verbose_name='season')),
                ('info', models.TextField(blank=True, max_length=300, null=True, verbose_name='information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registlation date')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='price')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'woman'), (3, 'child')], default=1, verbose_name='gender')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='add information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registlation date')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(default='defo', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'item',
            },
        ),
    ]
