# Generated by Django 3.1.1 on 2020-10-16 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, verbose_name='mail')),
                ('product_name', models.CharField(max_length=200, verbose_name='product_name')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='price')),
                ('sex', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registlation date')),
            ],
        ),
    ]
